name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cmake_test:
    name: CMake test (without otlp-exporter)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: setup
      run: |
        sudo ./ci/setup_cmake.sh
        sudo ./ci/setup_ci_environment.sh
    - name: run cmake tests (without otlp-exporter)
      run: |
        sudo ./ci/setup_thrift.sh
        ./ci/do_ci.sh cmake.test

  bazel_asan:
    name: Bazel asan config
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Mount Bazel Cache
      uses: actions/cache@v3
      env:
        cache-name: bazel_cache
      with:
        path: /home/runner/.cache/bazel
        key: bazel_asan
    - name: setup
      run: |
        sudo ./ci/setup_thrift.sh dependencies_only
        sudo ./ci/setup_ci_environment.sh
        sudo ./ci/install_bazelisk.sh
    - name: run tests
      run: ./ci/do_ci.sh bazel.asan

  bazel_tsan:
    name: Bazel tsan config
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Mount Bazel Cache
      uses: actions/cache@v3
      env:
        cache-name: bazel_cache
      with:
        path: /home/runner/.cache/bazel
        key: bazel_tsan
    - name: setup
      run: |
        sudo ./ci/setup_thrift.sh dependencies_only
        sudo ./ci/setup_ci_environment.sh
        sudo ./ci/install_bazelisk.sh
    - name: run tests
      run: ./ci/do_ci.sh bazel.tsan

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: sudo ./ci/install_format_tools.sh
    - name: run tests
      run: ./ci/do_ci.sh format

  markdown-lint:
    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@v3

    - name: install markdownlint-cli
      run: sudo npm install -g markdownlint-cli

    - name: run markdownlint
      run: markdownlint .

  misspell:
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v3
    - name: install misspell
      run: |
        curl -L -o ./install-misspell.sh https://git.io/misspell
        sh ./install-misspell.sh
    - name: run misspell
      run: ./bin/misspell -error .

  docfx_check:
    name: DocFX check
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: install docfx
      run: choco install docfx -y --version=2.58.5
    - name: run ./ci/docfx.cmd
      shell: cmd
      run: ./ci/docfx.cmd
